### ISSUE TITLE
iPad Pro 9.7" WIFI Error Says Unsupported

### ISSUE THREAD

**Issue by iSteve-O** [TSSSaver/TSSSaver#13]
When I enter my ECID and model for my 9.7" WIFI iPad Pro it goes to a screen that says the device is not supported (on the tsssaver.1conan.com website), but when I enter my ECID into the box to take me to my previously saved blobs it takes me right to my old blobs (verified good, used to upgrade to 10.2 from 9.3.3). I'm not sure if this is an issue with the source code or the site itself, so I apologize if this is not the appropriate place to post this issue. -Thanks!

**Comment by 1Conan** [comment]
This is an issue with the website's source code which is newer than the code here. 

Please email me or message me on reddit instead. (That said, I'll try fixing that ASAP)
