### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 2600box** [TSSSaver/TSSSaver#2]
*** Error in `./tsschecker': free(): invalid size: 0x0000000001e4b900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x0000000000dbd900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x0000000001719900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x00000000010a5900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x0000000001d73900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x0000000001442900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x00000000015ec900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x00000000009d2900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x0000000001b25900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x00000000013a8900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x0000000001bf0900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x0000000001fee900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x00000000023d5900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x000000000125c900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x00000000009a3900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x000000000165f900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x0000000000928900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x0000000001a2f900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x0000000002491900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x00000000026db900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x0000000002386900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x0000000001211900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x00000000012cd900 *** Aborted *** Error in `./tsschecker': free(): invalid size: 0x0000000000a59900 *** Aborted
Device identifier already added! iPhone9,3 (Force download starting.) 
https://tsssaver.1conan.com/shsh/48379xxxxxxx

**Comment by 1Conan** [comment]
This is not the support for the site.

This is for issues regarding the source.

**Comment by 2600box** [comment]
it would appear to be an issue in your source

**Comment by 1Conan** [comment]
No. 

That's an issue regarding the server. This has nothing to do with the code hosted here.
