### ISSUE TITLE
iPad Air j71ap/j72ap

### ISSUE THREAD

**Issue by c-hri-s** [TSSSaver/TSSSaver#20]
I have an iPad Air Wifi (not cellular).

Following the menus TSSSaver detects this as:

```
Done saving ECID! 
Device Identifier: iPad4,1 
ECID (Decimal): XXXXXXX
ECID (Hex): XXXXXXX
Board Config: j71ap 
```

However the iPad is actually iPad4,2 with board config j72ap (which TSSSaver thinks is an iPad Cellular)

From futurerestore:

```
INFO: device serial number is XXXXXXXXXXXX
Found device in Recovery mode
Identified device as j72ap, iPad4,2
```

This means that someone following the menus would end up with useless blobs (yes, that would be me).

**Comment by Tebela** [comment]
Following the menus TSSSaver detects this as:
(which TSSSaver thinks is an iPad Cellular)

SO I CAN‘T UNDERSTAND WHAT YOU MEAN!

THE TSSSAVER NEVER DETECTS ANY iDEVICE VERSION CAUSE IF YOU USE TSSSAVER TO SAVE YOUR BLOBS YOU HAVE TO SET THE RIGHT iDEVICE VERSION MANUALLY AND IF YOU SET IT MANUALLY TO iPAD4.1 IT IS YOUR OWN MISTAKE AND NOT A DETECT BUG IN TSSSAVER!

**Comment by c-hri-s** [comment]
Overlooking the rather childlike rant, the issue is with the mapping between the menu presented to the user and the devices mapped in https://github.com/TSSSaver/TSSSaver/blob/master/json/devices.json

Have you even run the code to see how it presents?

**Comment by Tebela** [comment]
No i always use the Website Service TSSSaver by Conan to Save my Blobs and there you have to choose it manually in my case for my iPhone7 GSM it‘s iPhone 9,3 

Mit freundlichen Grüßen:
Makko

Gesendet von myMail für iOS

Mittwoch, 11. Juli 2018, 15:11 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by Tebela** [comment]
This is how i did it and save my Device Blobs on this Site here:

https://tsssaver.1conan.com/

Mit freundlichen Grüßen:
Makko

Gesendet von myMail für iOS

Mittwoch, 11. Juli 2018, 15:11 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by c-hri-s** [comment]
Sure, so that's the site I use too. The issue is that when you select iPad Air (Wifi) it fetches blobs for an iPad4,1 and my iPad Air Wifi seems to be an iPad 4,2, but I'll confirm.

**Comment by Tebela** [comment]
Oh really?

Ok thats really Bad Shit and they have to fix this bug otherwise many People get corrupted blobs without knowing 


Mit freundlichen Grüßen:
Makko

Gesendet von myMail für iOS

Mittwoch, 11. Juli 2018, 15:40 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by Tebela** [comment]
I think you have wrong informations.

The iPad Air (Wifi) has ID (iPad 4,1)




Mit freundlichen Grüßen:
Makko

Gesendet von myMail für iOS

Mittwoch, 11. Juli 2018, 15:40 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by Tebela** [comment]
If you choose iPad as the Device and iPad Air (Wifi) TSSSaver will catch Shsh for (iPad4,1) that is correct!

Mit freundlichen Grüßen:
Makko

Gesendet von myMail für iOS

Mittwoch, 11. Juli 2018, 15:40 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by c-hri-s** [comment]
I appreciate that, so either:

1. I have a cellular iPad (which I don't)
2. There are ipad4,2 Wifi units which exist
3. futurerestore incorrectly detects my iPad as a 4,2

I'm going to check in iTunes what model it reports and go from there.

**Comment by Tebela** [comment]
There are 3 different iPad Air Models released


These are the following one‘s:

iPad Air (China)

Boardconfig: j73ap
Model: iPad4,3

—-

iPad Air (Cellular)

Boardconfig: j72ap
Model: iPad4,2

—-

iPad Air (WiFi)

Boardconfig: j71ap
Model: iPad4,1

—-

Not known about any other iPad Air Wifi Models



Mit freundlichen Grüßen:
Makko

Gesendet von myMail für iOS

Mittwoch, 11. Juli 2018, 16:17 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by Tebela** [comment]
If you have a cellular iPad and you don't know which one it is then you can go to the AppStore and search for the App "Lirum Device Info Lite" and install it.
You also Coups install it by this directlink 

After Installation you should Open the App and klick "This Device" and then klick General and there you can see which iPad it is!



Mit freundlichen Grüßen:
Makko



- Gesendet von myMail für iOS

Mittwoch, 11. Juli 2018, 16:17 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by c-hri-s** [comment]
Okay, hold my hands up - it's a cellular iPad and I never knew.
Sorry :)

**Comment by Tebela** [comment]
It’s an iPad Air cellular?
But you didn‘t noticed that it has a SIM Eject bracket?

Muhahahahaaa...

No problem Amigo but if it’s an iPad Air Celluar then all blobs you have saved in the past are invalid blobs and you can‘t use them to Restore to an unsigned iOS with Prometheus/Futurestore. 

Damn that‘s hard news

Mit freundlichen Grüßen:
Makko

Gesendet von myMail für iOS

Freitag, 13. Juli 2018, 15:56 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by Tebela** [comment]
Everytime you turned on your iPad you should have seen that popup (no sim card) thats the Info that this iPad was an Cellular ipad
