### ISSUE TITLE
Re-introduce support for model identifiers

### ISSUE THREAD

**Issue by kabiroberai** [TSSSaver/TSSSaver#3]
Commit 0ed9324dfa83df05257eaced42aaec582deff53c replaces the model identifier text field with a dropdown to choose a model. Whilst this is extremely useful, it would be great if there was also an option to enter the model identifier as listed in iTunes (eg. `iPhone9,4`).

To achieve this, you could add an `Other` option to `#deviceType`, which replaces `#deviceModel` with a text field in which they can enter their model ID.

This is beneficial as it allows copying the model identifier from iTunes, in case one doesn't know whether their device is GSM, CDMA, or Global. Since the user needs to open iTunes for their ECID anyways, it doesn't require any extra steps.

**Comment by 1Conan** [comment]
I've been thinking of another way to do it.

Append that data to the list, or just adding an option to manually specify it.
We can just append it to the selections. This is quite easier to do since it doesn't need that much manipulation in javascript. (Easy to do in jQuery but I don't want a lot of external dependencies)
For example, in this file, json/iPhone.json modify the strings like this
```
[
    "iPhone 2G (iPhone1,1)"
]
```

Gonna take a bit of time though. I'm quite busy since it's holiday season.
If anyone wants to do this, just make a pull request :)

**Comment by kabiroberai** [comment]
I think an even better way to do this would be to generate the entire model list server-side and then only show the specified `select` list. This would come with the added benefit of reducing network load, as a client-side call to `json/<device type>.json` would not need to be made. Example of generated HTML (untested):

```html
<select id="deviceType" name="deviceType">
    <option value="iPhone">iPhone</option>
    <option value="iPod">iPod</option>
    <option value="iPad">iPad</option>
    <option value="AppleTV">AppleTV</option>
</select>

<select id="iPhone" class="deviceModel" name="deviceModel">
    <option value="0">iPhone 2G (iPhone1,1)</option>
    …
</select>
…
<script>
    …
    document.getElementById('deviceType').onchange = function(e) {
        var modelPickers = document.getElementsByClassName("deviceModel");
        for (var i = 0; i < modelPickers.length; i++) {
            modelPickers[i].style.display = "none";
        }
        document.getElementById(e.target.value).style.display = "";
    }
</script>
```

**Comment by 1Conan** [comment]
If we had several select elements with name="deviceModel", that would be a problem .-.

**Comment by kabiroberai** [comment]
Couldn't you just remove the name from the unselected ones?

**Comment by kabiroberai** [comment]
Or just change it to something else:
```html
<script>
    …
    document.getElementById('deviceType').onchange = function(e) {
        var modelPickers = document.getElementsByClassName("deviceModel");
        for (var i = 0; i < modelPickers.length; i++) {
            modelPickers[i].style.display = "none";
            modelPickers[i].name = "deviceModelUnselected";
        }
        document.getElementById(e.target.value).style.display = "";
        document.getElementById(e.target.value).name = "deviceModel";
    }
</script>
```

**Comment by 1Conan** [comment]
Well that's fine. I'll try working on that. The discord bot is the priority though :D

**Comment by 1Conan** [comment]
Closed. The dropdown thing was the one implemented in the new UI. (ETA SON)
