### ISSUE TITLE
--Boardconfig

### ISSUE THREAD

**Issue by alessandro893** [TSSSaver/TSSSaver#5]
Add please this in your code:

            $cmd .= " --boardconfig ".escapeshellarg($deviceInfo['boardconfig']);

and edit mysql db, add boardconfig:

CREATE TABLE `devices` (
  `deviceIdentifier` text NOT NULL,
  `deviceType` text NOT NULL,
  `deviceID` text NOT NULL,
  `deviceECID` bigint(20) NOT NULL,
  `boardconfig` text NOT NULL,
  PRIMARY KEY (`deviceECID`),
  UNIQUE KEY `deviceECID` (`deviceECID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

**Comment by 1Conan** [comment]
I added it already on the site when tsschecker was updated. The repo will be updated soon. (I still need to clean the new code)

**Comment by felipedrumond** [comment]
Hi @1Conan! I resubmitted my ECID for both iPhone and iPad. About the iPhone (6s), I had to inform "N71AP" and "N71mAP" as my Board Configuration. The file generated is from December 20th, and not a new one. Is that correct? Why my blobs weren't generated again? Am I safe with that December-20th version?

**Comment by 1Conan** [comment]
@felipedrumond
This is not a support thread. Github issues is not for support as well. (This is for the source code)

Just submit your ECID again

Anyways,
