### ISSUE TITLE
tsss saver

### ISSUE THREAD

**Issue by ashishagravat** [TSSSaver/TSSSaver#8]
hi 
some time ago im saved my iphone 6s shsh ios 10.2 but using that shsh can't restore my phone 
than im check blobs so im save shsh blobs using n71ap Board Configuration but im checkblobs using 
tss saver so its see Board Configuration is n61ap so how to solve 
any mathod to edit blobs

**Comment by 1Conan** [comment]
its a bug with tsschecker before. This is not an issue with my code.

Please go to the discord server for support. GitHub issues aren't for this.
