### ISSUE TITLE
Device Identifier not recognized! ipad6,12

### ISSUE THREAD

**Issue by josef-brozik** [TSSSaver/TSSSaver#9]
hello,

If "iPad 5 (Cellular)" is selected than it ends with "Device Identifier not recognized! ipad6,12"
but iPad 5 (WiFi) works ok (I have both devices)

I think there is some typo in Cellular option, could you please look at it?

Thank you

**Comment by 1Conan** [comment]
This has been fixed

Also, this is not a support forum! Go to the discord for support. https://discord.gg/dTunaXa
